markdown: redcarpet
baseurl: /
exclude: ['runLocal.sh', 'README.md', '.gitignore']
lsi: false
 safe: true
 source: [./]
 incremental: false
 highlighter: rouge
 gist:
   noscript: false
 kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge
